### ISSUE TITLE
show-routes command results in a KeyError

### ISSUE THREAD

**Issue by kremerpatrick** [vmware/python-client-for-vmware-cloud-on-aws#124]
### Describe the bug

The route type argument was converted to a positional argument, but it's specified as `route-type` in argparse, and it's checked for as `route_type` in getSDDCroutes()

### Reproduction steps

1. python .\pyVMC.py system show-routes t0

Traceback (most recent call last):
  File "C:\Users\kremerpt\git\Flings\python-client-for-vmware-cloud-on-aws\pyVMC.py", line 4701, in <module>     
    main()
  File "C:\Users\kremerpt\git\Flings\python-client-for-vmware-cloud-on-aws\pyVMC.py", line 4697, in main
    args.func(**params)
  File "C:\Users\kremerpt\git\Flings\python-client-for-vmware-cloud-on-aws\pyVMC.py", line 2248, in getSDDCroutes
    if kwargs['route_type'] == 't0':
KeyError: 'route_type'

### Expected behavior

The command should return the t0 route table

**Comment by BillRothVMware** [comment]
works for me.
