### ISSUE TITLE
Show SDDC Connected VPC errors out

### ISSUE THREAD

**Issue by kremerpatrick** [vmware/python-client-for-vmware-cloud-on-aws#187]
### Describe the bug

sddc show-sddc-connected-vpc results in an error

### Reproduction steps

1. python .\pyVMC.py sddc show-sddc-connected-vpc

After some time, the command fails with this dump:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kremerpt\git\Flings\python-client-for-vmware-cloud-on-aws\pyVMC.py", line 1409, in <module>
    main()
  File "C:\Users\kremerpt\git\Flings\python-client-for-vmware-cloud-on-aws\pyVMC.py", line 1404, in main
    args.func(**params)
  File "C:\Users\kremerpt\git\Flings\python-client-for-vmware-cloud-on-aws\pyvmc_fxns.py", line 909, in getSDDCConnectedVPC
    json_response = get_conencted_vpc_json(proxy_url, session_token)
  File "C:\Users\kremerpt\git\Flings\python-client-for-vmware-cloud-on-aws\pyvmc_nsx.py", line 389, in get_conencted_vpc_json
    json_response = response.json()
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Expected behavior

Command should return connected VPC info.

**Comment by maulepilot117** [comment]
What SDDC version are you testing against?  API changes happened between M16 and M18.

**Comment by fr0gger03** [comment]
Also, be sure your refresh token and SDDC ID are correct and up to date.  Works for me:

<img width="1302" alt="2023-05-09_12-09-13" src="https://github.com/vmware/python-client-for-vmware-cloud-on-aws/assets/5892826/f000dd48-de81-4e08-bb1b-5d7bc34a4445">

**Comment by kremerpatrick** [comment]
Apparently some transient API issue, it was happening across multiple SDDCs both M18 and M22. Came back a few hours later and the same SDDCs work fine.
